export const APP_ROUTES = {
  LOGIN: 'login',
  COURSE: 'course',
  STUDENT: 'student',
  STUDENTS: 'students',
  MENTOR: 'mentor',
  INTERVIEWS: 'interviews',
  REGISTER_STUDENT: 'registry/student',
  REGISTER_MENTOR: 'registry/mentor',
  DASHBOARD: 'dashboard',
  SELECT_ROLE: 'select-role',
  MENTOR_DASHBOARD: 'mentor/dashboard',
  ADMIN_DASHBOARD: 'admin/dashboard',
  PROFILE: 'profile',
  SCORE: 'score',
  SCHEDULE: 'schedule',
  AUTOTEST: 'auto-test',
  USER: 'user',
  ABOUT: 'about',
  STATS: 'stats',
  SETTINGS: 'settings',
  ADMIN: 'admin',
  TDISTRIBUTIONS: 'team-distributions',
  EXPELSTUDENT: 'expel-student',
  CCSUBMIT: 'cross-check-submit',
  CCREVIEW: 'cross-check-review',
} as const;
