name: Angular CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Lint code
        run: pnpm run lint:check

      - name: Run tests
        run: pnpm run test:ci

      - name: Create environment files
        run: |
          echo "export const environment = { production: true, firebaseConfig: { apiKey: '${{ secrets.FIREBASE_API_KEY }}', authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}', projectId: '${{ secrets.FIREBASE_PROJECT_ID }}', storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}', messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}', appId: '${{ secrets.FIREBASE_APP_ID }}' } };" > src/environments/environment.prod.ts
          echo "export const environment = { production: false, firebaseConfig: { apiKey: '${{ secrets.FIREBASE_API_KEY }}', authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}', projectId: '${{ secrets.FIREBASE_PROJECT_ID }}', storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}', messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}', appId: '${{ secrets.FIREBASE_APP_ID }}' } };" > src/environments/environment.ts

      - name: Build project
        run: pnpm run build
