name: Angular CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run format:check

      - name: Lint code
        run: pnpm run lint:check

      - name: Run tests
        run: pnpm run test:ci

      - name: Build project
        run: pnpm run build
